### ISSUE TITLE
Feature request - multiple values for trusted_gid

### ISSUE THREAD

**Issue by NuxRo** [cormander/tpe-lkm#10]
Seems like the main dev is on a roll, so trying to take advantage and requesting a feature. :-)

Can we haz multiple values for trusted_gid or admin_gid? Sometimes I want to exclude from tpe certain scripts owned by e.g. CPanel via different gids, I'm sure there would be other practical use cases.

**Comment by cormander** [comment]
The addition of the xattr support for soften flags should help with misbehaving apps of different gids.

**Comment by NuxRo** [comment]
Thanks Cory, I'll look this up next time I put tpe on cpanel.
