### ISSUE TITLE
Possibility for 4.x kernels ? 

### ISSUE THREAD

**Issue by bozb** [cormander/tpe-lkm#12]
Hello, 

Any possibility of this getting support for 4.x ++ kernels , i find it very useful ? 

Thanks !

**Comment by cormander** [comment]
I've mostly only been maintaining it for kernels that are used by Red Hat Enterprise, but am willing to merge in submissions for newer kernels.

**Comment by cormander** [comment]
With the recent move to ftrace, 4.x kernels compile with this module.
