### ISSUE TITLE
Unable to insert module, ftrace is not enabled

### ISSUE THREAD

**Issue by gyted** [cormander/tpe-lkm#21]
Sorry for disturbing you again but I can't load tpe module:
```
sudo modprobe tpe
modprobe: ERROR: could not insert 'tpe': Function not implemented

sudo dmesg |grep tpe
tpe: Unable to insert module, ftrace is not enabled
```
```
zcat /proc/config.gz | grep TRACER
# CONFIG_ATH5K_TRACER is not set
CONFIG_NOP_TRACER=y
CONFIG_HAVE_FUNCTION_TRACER=y
CONFIG_HAVE_FUNCTION_GRAPH_TRACER=y
CONFIG_TRACER_MAX_TRACE=y
CONFIG_CONTEXT_SWITCH_TRACER=y
CONFIG_GENERIC_TRACER=y
CONFIG_FUNCTION_TRACER=y
CONFIG_FUNCTION_GRAPH_TRACER=y
# CONFIG_IRQSOFF_TRACER is not set
# CONFIG_PREEMPT_TRACER is not set
CONFIG_SCHED_TRACER=y
CONFIG_HWLAT_TRACER=y
CONFIG_TRACER_SNAPSHOT=y
# CONFIG_TRACER_SNAPSHOT_PER_CPU_SWAP is not set
CONFIG_STACK_TRACER=y
```
```
zcat /proc/config.gz | grep FTRACE
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_STM_SOURCE_FTRACE=m
# CONFIG_PSTORE_FTRACE is not set
CONFIG_HAVE_DYNAMIC_FTRACE=y
CONFIG_HAVE_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y
CONFIG_FTRACE=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_DYNAMIC_FTRACE=y
CONFIG_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_FTRACE_MCOUNT_RECORD=y
# CONFIG_FTRACE_STARTUP_TEST is not set
```
```
sudo sysctl -a |grep ftrace
kernel.ftrace_dump_on_oops = 0
kernel.ftrace_enabled = 1
```
```
findmnt |grep debugfs
│ ├─/sys/kernel/debug   debugfs debugfs rw,relatime
```

**Comment by cormander** [comment]
This is due to a run time safety check that's failing. Can you give me the output of this command?

`grep ftrace_enabled /proc/kallsyms`

For example:

    $ grep ftrace_enabled /proc/kallsyms
    ffffffff81140480 t ftrace_enabled_open
    ffffffff816c0700 r ftrace_enabled_fops
    ffffffff81ae40e0 D ftrace_enabled
    ffffffff81e6abc4 b kprobe_ftrace_enabled
    ffffffff81ee9388 b last_ftrace_enabled

What's happening is it can't find the `ftrace_enabled` symbol - or it contains something it doesn't expect.

**Comment by cormander** [comment]
Also, I pushed cb8289c164ec7b2b15cf451e161c9dcd30c07cc0 which adds additional logging when there's a problem. You'll see it by running the below after module insert:
`sudo dmesg | grep fopskit`

**Comment by gyted** [comment]
```
grep ftrace_enabled /proc/kallsyms
ffffffffa112b870 t ftrace_enabled_open
```
```
sudo dmesg | grep fopskit
fopskit: fopskit_find_sym_addr() failed with return code -14 for fops_hook { name => ftrace_enabled, addr => 0, found => 0, hooked => 0 } at fopskit_find_sym_addr() line 217
```

**Comment by cormander** [comment]
Do you have the kernel.kptr_restric sysctl enabled? Arch Linux appears to enable this by default and may be what's causing the issue. See:

https://bugs.archlinux.org/task/34323

I downloaded the kernel-ml-4.11 package on my CentOS system and this module still goes in fine.

**Comment by gyted** [comment]
I had it enabled previously. Above results are with `kernel.kptr_restric sysctl=0`.
With  `kernel.kptr_restric sysctl=1` it looks like this:
```
grep ftrace_enabled /proc/kallsyms
0000000000000000 t ftrace_enabled_open
```

**Comment by cormander** [comment]
Do you have CONFIG_DEBUG_INFO=y set in the kernel? I'm also reading how archlinux strips some symbols from the kernel while packaging. If this is the case, symbol address discovery would only be possible with a corresponding System.map of the running kernel, which adds risk of causing a fault on module insert. I haven't used archlinux before, so addressing this issue may take me some time.

**Comment by gyted** [comment]
```
zcat /proc/config.gz | grep CONFIG_DEBUG_INFO
# CONFIG_DEBUG_INFO is not set
```
Should I recompile it?

**Comment by cormander** [comment]
This module is meant to be inserted into precompiled distribution kernels. If you're compiling your own, the better approach is to include tpe at compile time. This module will require some changes to get that enabled - would you prefer that approach?

**Comment by gyted** [comment]
`# CONFIG_DEBUG_INFO is not set` is the default option in every Arch kernel, I didn't touch it. Anyway enabling this didn't change anything.

I really don't want to add more burden on you. Of course I can try compiling it with kernel if it's available but if I'm only one who needs this it wouldn't be worth your time.

**Comment by cormander** [comment]
Testing on `Linux archiso 4.10.13-1-ARCH`, if I simply remove the `ftrace_enabled` check:

    diff --git a/tpe_module.c b/tpe_module.c
    index db57dce..745f733 100644
    --- a/tpe_module.c
    +++ b/tpe_module.c
    @@ -186,13 +186,6 @@ static struct fops_cred_handler tpe_cred_handler = {
     static int __init tpe_init(void) {
            int i, ret;
    
    -       ret = fopskit_sym_int("ftrace_enabled");
    -
    -       if (!ret || IN_ERR(ret)) {
    -               printk(PKPRE "Unable to insert module, ftrace is not enabled.\n");
    -               return -ENOSYS;
    -       }
    -
            ret = fopskit_init_cred_security(&tpe_cred_handler);
    
            if (IN_ERR(ret))

It compiles and inserts just fine. Test suite passes. Except, when I `rmmod tpe` - the kernel panics. The stack trace shows `kernel BUG  at mm/cmalloc.c:15471` and none of the symbols on the stack are TPE related. Just an FYI.

Please compile with the above patch, and test on your system, letting me know if it faults when you do the `rmmod tpe`.

Thanks,

**Comment by cormander** [comment]
Pushed commit 44e9f0a5daf12892fe445ce2288fa6b6f9cbf3c5 which moves the `ftrace_enabled` check to where it's really needed, which isn't a code path taken on archlinux. Please let me know if this resolves the issue for you.

**Comment by gyted** [comment]
```
sudo modprobe tpe
fopskit: fopskit_find_sym_addr() failed with return code -14 for fops_hook { name => selinux_enabled, addr => 0, found => 0, hooked => 0 } at fopskit_find_sym_addr() line 223
fopskit: fopskit_find_sym_addr() failed with return code -14 for fops_hook { name => selinux_disabled, addr => 0, found => 0, hooked => 0 } at fopskit_find_sym_addr() line 223
tpe: warning: cred->security was not remapped; the soften_mmap flag won't persist to child processes.
tpe: added to kernel
```
Module loaded. Arch didn't enable selinux by default. Could this be the issue? I enabled softmode in tpe config.
`sudo rmmod tpe`
[dmesg.txt](https://github.com/cormander/tpe-lkm/files/980831/dmesg.txt)
Kernel didn't panic. Module unloaded.

**Comment by cormander** [comment]
Ok so you're at least now in a working state. Don't turn on SELinux - you'll then fail to inset the module, as the ftrace_enabled check only happens if SELinux is enabled. What happens if it is, is soften_mmap xattr flags, is any exist, will persist to child processes. Mostly this is only needed on desktops (Gnome) and byte compile build machines (such as Jenkins). It's only bee tested on kernels with SELinux, and I turn it off at insert time if it isn't enabled for safety. The cred->remap could collide with how other security module alloc memory.

Closing this issue since you're in a working state. If you so desire, send along that module unload dmesg to archlinux. It doesn't happen on my system with an unmodified 4.11 vanilla kernel.
