### ISSUE TITLE
In-tree build

### ISSUE THREAD

**Issue by sempervictus** [cormander/tpe-lkm#24]
Is there a way to build the module in-tree such that it's actually built into the kernel, not as a separate, un-loadable module?
Thanks for writing this - very educational.

**Comment by cormander** [comment]
It's possible, but I've never tried as maintaining a kernel build is out of scope of my goals. I'm happy to accept a PR for it though, if you figure it out.

As far as it being an un-loadable module, just do this and you can't un-load it:

    sudo sysctl kernel.modules_disabled=1

**Comment by cormander** [comment]
Feel free to re-open this if you decide to make any changes to get the module to build in-tree, and I'll merge it in.
