### ISSUE TITLE
How to define trusted gid ?

### ISSUE THREAD

**Issue by bryn1u** [cormander/tpe-lkm#36]
Hey,

First i want to thanks for your work. I was using grsecurity tpe when was free. Today i have found your project and looks great but i have a still problem, how to define trusted group for users who will be able to run some app or script. How can i set that group ?

Thanks !

**Comment by cormander** [comment]
In the “Configuration” section of the README it shows many values you can set with the sysctl command. The “trusted_gid” is one of them.
